FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyEventz.API.csproj", "./"]
RUN dotnet restore "./MyEventz.API.csproj"
COPY . .
RUN dotnet publish "MyEventz.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MyEventz.API.dll"]
